name: .NET Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    name: Build and test
    runs-on: windows-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET SDK 6.0 LTS
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
   # - name: Download Azure Functions Core Tools
   #   uses: suisei-cn/actions-download-file@v1
   #   id: downloadfile
   #   with:
   #     name: Function V4 tools
   #     url: "https://alonfileshare.blob.core.windows.net/alonshare/func-cli-x64.msi?sp=r&st=2022-01-17T13:17:20Z&se=2024-01-17T21:17:20Z&sv=2020-08-04&sr=b&sig=d59%2FgSLx2yqrWipBZK48%2Fy2pKHi9AR6jZmttwIBSszs%3D"
    #- name: Install Azure Functions Core Tools
    #  shell: pwsh
    #  run: Start-Process msiexec.exe -Wait -ArgumentList '/I func-cli-x64.msi /quiet'
    - name: func 4.x
      run: npm i azure-functions-core-tools@4 --unsafe-perm true 
    - name: Build
      run: dotnet build --no-restore 
    - name: 'Install Cosmos Emulator'
      uses: southpolesteve/cosmos-emulator-github-action@v1
    - name: Install Azurite
      id: azuright
      uses: potatoqualitee/azuright@v1.1
      with:
        self-signed-cert: true
    
    - name: Start function apps
      shell: pwsh
      run: |
            $rootDir = $pwd.Path
           
            cd ./Services/HttpTriggerQueueOutput
            Start-Process -NoNewWindow .\node_modules\azure-functions-core-tools\bin\func.exe -ArgumentList "host","start","--port","7071"
            Start-Sleep -s 40
            
            cd $rootDir/Services/QueueTriggerCosmosOutput
            Start-Process -NoNewWindow .\node_modules\azure-functions-core-tools\bin\func.exe -ArgumentList "host","start","--port","7072"
            Start-Sleep -s 40
            netstat -lt
            cd $rootDir/Tests/HttpTriggerQueueOutputTest
            dotnet test . -c Debug
            cd $rootDir/Tests/QueueTriggerCosmosOutputTest
            dotnet test . -c Debug
            cd $rootDir/Tests/HttpTriggerCosmosOutputTest
            dotnet test . -c Debug
            
            cd $rootDir  

