name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET SDK 6.0 LTS
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Setup Azure Functions Core Tools
      shell: bash
      run: |
        #npm install -g azure-functions-core-tools@3 --unsafe-perm true
        wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install azure-functions-core-tools-4

    - name: Build
      run: dotnet build --no-restore 
    
    - name: Start containers
      run: docker-compose -f "DevOps/docker-compose.yml" up -d --build
    - name: Copy certificate from CosmosDB Emulator
      shell: bash
      run: |
           sleep 60
           sudo apt-get install ca-certificates -y
           ipaddr="`ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}' | head -n 1`"
           sudo curl -k https://$ipaddr:8081/_explorer/emulator.pem > emulator.cert
           sudo cp emulator.cert /usr/local/share/ca-certificates/emulatorcert.crt
           sudo update-ca-certificates --verbose
           
    - name: Start function apps
      shell: pwsh
      run: |
            $rootDir = $pwd.Path

            cd ./Services/HttpTriggerQueueOutput
            Start-Process -NoNewWindow func -ArgumentList "host","start","--port","7071"
            Start-Sleep -s 10
            
            cd $rootDir/Services/QueueTriggerCosmosOutput
            Start-Process -NoNewWindow func -ArgumentList "host","start","--port","7072"
            Start-Sleep -s 10

            cd $rootDir/Tests/HttpTriggerQueueOutputTest
            dotnet test . -c Debug
            cd $rootDir/Tests/QueueTriggerCosmosOutputTest
            dotnet test . -c Debug
            cd $rootDir/Tests/HttpTriggerCosmosOutputTest
            dotnet test . -c Debug
            
            cd $rootDir  

