name: .NET Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET SDK 6.0 LTS
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Setup Azure Functions Core Tools
      shell: bash
      run: |
        wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install azure-functions-core-tools-4

    - name: Build
      run: dotnet build --no-restore 
    
    - name: Start containers
      run: docker-compose -f "DevOps/docker-compose.yml" up -d --build
    - name: Copy certificate from CosmosDB Emulator
      shell: bash
      run: |
           sleep 60
           EMULATOR_HOST=localhost
           EMULATOR_PORT=8081
           EMULATOR_CERT_PATH=/tmp/cosmos_emulator.cert
           openssl s_client -connect ${EMULATOR_HOST}:${EMULATOR_PORT} </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > $EMULATOR_CERT_PATH
           sudo cp $EMULATOR_CERT_PATH /usr/local/share/ca-certificates/cosmos_emulator.crt
           sudo update-ca-certificates

    - name: Start function apps
      shell: pwsh
      run: |
            $rootDir = $pwd.Path

            cd ./Services/HttpTriggerQueueOutput
            Start-Process -NoNewWindow func -ArgumentList "host","start","--port","7071"
            Start-Sleep -s 40
            
            cd $rootDir/Services/QueueTriggerCosmosOutput
            Start-Process -NoNewWindow func -ArgumentList "host","start","--port","7072"
            Start-Sleep -s 40
            netstat -lt
            cd $rootDir/Tests/HttpTriggerQueueOutputTest
            dotnet test . -c Debug
            cd $rootDir/Tests/QueueTriggerCosmosOutputTest
            dotnet test . -c Debug
            cd $rootDir/Tests/HttpTriggerCosmosOutputTest
            dotnet test . -c Debug
            
            cd $rootDir  

