name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    name: Build and test
    runs-on: windows-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET SDK 6.0 LTS
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Setup Azure Functions Core Tools
      shell: pwsh
      run: |
        npm i -g azure-functions-core-tools@4 --unsafe-perm true

    - name: Build
      run: dotnet build --no-restore 
    
    - uses: southpolesteve/cosmos-emulator-github-action@v1
    - name: 'npm ci'
      run: npm ci
    - name: 'npm test'
      run: npm test

    - name: Install Azurite
      id: azuright
      uses: potatoqualitee/azuright@v1.1
      with:
        self-signed-cert: true

    
    - name: Start function apps
      shell: pwsh
      run: |
            $rootDir = $pwd.Path

            cd ./Services/HttpTriggerQueueOutput
            Start-Process -NoNewWindow func -ArgumentList "host","start","--port","7071"
            Start-Sleep -s 40
            
            cd $rootDir/Services/QueueTriggerCosmosOutput
            Start-Process -NoNewWindow func -ArgumentList "host","start","--port","7072"
            Start-Sleep -s 40
            netstat -lt
            cd $rootDir/Tests/HttpTriggerQueueOutputTest
            dotnet test . -c Debug
            cd $rootDir/Tests/QueueTriggerCosmosOutputTest
            dotnet test . -c Debug
            cd $rootDir/Tests/HttpTriggerCosmosOutputTest
            dotnet test . -c Debug
            
            cd $rootDir  

