name: .NET Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    name: Build and test
    runs-on: windows-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET SDK 6.0 LTS
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Download Azure Functions Core Tools
      uses: suisei-cn/actions-download-file@v1
      id: downloadfile
      with:
        name: Function V4 tools
        url: "https://go.microsoft.com/fwlink/?linkid=2174087"
        target: .
    - name: Install Azure Functions Core Tools
      shell: pwsh
      run: Start-Process msiexec.exe -Wait -ArgumentList '/I func-cli-x64.msi /quiet'
    - name: Build
      run: dotnet build --no-restore 
    - name: 'Install Cosmos Emulator'
      uses: southpolesteve/cosmos-emulator-github-action@v1
    - name: Install Azurite
      id: azuright
      uses: potatoqualitee/azuright@v1.1
      with:
        self-signed-cert: true
    
    - name: Start function apps
      shell: pwsh
      run: |
            $rootDir = $pwd.Path

            cd ./Services/HttpTriggerQueueOutput
            Start-Process -NoNewWindow func -ArgumentList "host","start","--port","7071"
            Start-Sleep -s 40
            
            cd $rootDir/Services/QueueTriggerCosmosOutput
            Start-Process -NoNewWindow func -ArgumentList "host","start","--port","7072"
            Start-Sleep -s 40
            netstat -lt
            cd $rootDir/Tests/HttpTriggerQueueOutputTest
            dotnet test . -c Debug
            cd $rootDir/Tests/QueueTriggerCosmosOutputTest
            dotnet test . -c Debug
            cd $rootDir/Tests/HttpTriggerCosmosOutputTest
            dotnet test . -c Debug
            
            cd $rootDir  

